export const REFLECTION_CORE_CASE_FILE = {
	id: "reflection-core",
	title: "Reflection Core",
	description:
		"The final archive proves MIRROR was not just surveillance. Reflection Lab was the real core, and Helix Labs was the operational facade.",
	status: "ACTIVE",
	threatLevel: "ELEVATED",
	documents: [
		{
			id: "reflection-prime-statute",
			titleKey: "reflection.documents.primeStatute.title",
			title: "MIRROR PRIME Final Charter",
			category: "Internal Memo",
			classification: "Restricted",
			author: "Helix Continuity Office",
			contentKey: "reflection.documents.primeStatute.content",
			tags: "mirror,prime,continuity",
			createdAt: "2041-10-09T05:01:00.000Z",
			isFlagged: true,
			evidenceTags: ["mirror-prime-core"]
		},
		{
			id: "continuity-board-minutes",
			titleKey: "reflection.documents.boardMinutes.title",
			title: "Continuity Board Minutes",
			category: "Report",
			classification: "Restricted",
			author: "Helix Continuity Board",
			contentKey: "reflection.documents.boardMinutes.content",
			tags: "board,omega-7,continuity",
			createdAt: "2041-10-09T05:08:00.000Z",
			isFlagged: true,
			evidenceTags: ["continuity-board-minutes", "board-000-signature", "omega-7-directive"]
		},
		{
			id: "reflection-lab-blueprint",
			titleKey: "reflection.documents.blueprint.title",
			title: "Reflection Lab / Sublevel R-7 Blueprint",
			category: "Map",
			classification: "Restricted",
			author: "Helix Facilities Archive",
			contentKey: "reflection.documents.blueprint.content",
			tags: "reflection lab,r-7,core",
			createdAt: "2041-10-09T05:12:00.000Z",
			isFlagged: true,
			evidenceTags: ["reflection-lab-blueprint"]
		},
		{
			id: "replica-integrity-report",
			titleKey: "reflection.documents.replicaIntegrity.title",
			title: "Behavioral Replica Integrity Report",
			category: "Report",
			classification: "Restricted",
			author: "Behavioral Systems Archive",
			contentKey: "reflection.documents.replicaIntegrity.content",
			tags: "replicas,employees,prediction",
			createdAt: "2041-10-09T05:18:00.000Z",
			isFlagged: true,
			evidenceTags: ["replica-integrity-report", "behavioral-replica-map"]
		},
		{
			id: "selene-arendt-sealed-statement",
			titleKey: "reflection.documents.arendtStatement.title",
			title: "Sealed Statement of Dr. Selene Arendt",
			category: "Note",
			classification: "Unverified",
			author: "Dr. Selene Arendt",
			contentKey: "reflection.documents.arendtStatement.content",
			tags: "arendt,replicas,warning",
			createdAt: "2041-10-09T05:24:00.000Z",
			isFlagged: true,
			evidenceTags: ["selene-arendt-statement", "behavioral-replica-map"]
		},
		{
			id: "omega-7-protocol",
			titleKey: "reflection.documents.omega7.title",
			title: "Protocol OMEGA-7",
			category: "Internal Memo",
			classification: "Restricted",
			author: "Helix Continuity Board",
			contentKey: "reflection.documents.omega7.content",
			tags: "omega-7,relay,reflection lab",
			createdAt: "2041-10-09T05:29:00.000Z",
			isFlagged: true,
			evidenceTags: ["omega-7-directive", "mvoss-01-admin-token", "relay-omega-isolation-log"]
		}
	],
	emails: [
		{
			id: "reflection-email-prediction",
			fromName: "Selene Arendt",
			fromEmail: "s.arendt@helix.local",
			toName: "Elias Ren",
			toEmail: "e.ren@helix.local",
			subjectKey: "reflection.emails.prediction.subject",
			subject: "Prediction is not surveillance",
			bodyKey: "reflection.emails.prediction.body",
			body: "",
			folder: "Inbox",
			sentAt: "2041-10-09T05:03:00.000Z",
			isFlagged: true,
			evidenceTags: ["selene-arendt-statement", "replica-integrity-report"]
		},
		{
			id: "reflection-email-helix-can-burn",
			fromName: "Mara Voss",
			fromEmail: "m.voss@helix.local",
			toName: "Helix Continuity Board",
			toEmail: "continuity.board@helix.local",
			subjectKey: "reflection.emails.helixBurn.subject",
			subject: "Helix can burn, R-7 cannot",
			bodyKey: "reflection.emails.helixBurn.body",
			body: "",
			folder: "Security",
			sentAt: "2041-10-09T05:10:00.000Z",
			isFlagged: true,
			evidenceTags: ["mvoss-01-admin-token", "omega-7-directive"]
		},
		{
			id: "reflection-email-authorize-omega7",
			fromName: "Continuity Board",
			fromEmail: "continuity.board@helix.local",
			toName: "Mara Voss",
			toEmail: "m.voss@helix.local",
			subjectKey: "reflection.emails.authorizeOmega.subject",
			subject: "Authorize Omega-7",
			bodyKey: "reflection.emails.authorizeOmega.body",
			body: "",
			folder: "Announcements",
			sentAt: "2041-10-09T05:14:00.000Z",
			isFlagged: true,
			evidenceTags: ["board-000-signature", "omega-7-directive"]
		},
		{
			id: "reflection-email-model-exits",
			fromName: "Elias Ren",
			fromEmail: "e.ren@helix.local",
			toName: "Selene Arendt",
			toEmail: "s.arendt@helix.local",
			subjectKey: "reflection.emails.modelExits.subject",
			subject: "The model is choosing exits",
			bodyKey: "reflection.emails.modelExits.body",
			body: "",
			folder: "Inbox",
			sentAt: "2041-10-09T05:20:00.000Z",
			isFlagged: true,
			evidenceTags: ["mirror-prime-core", "behavioral-replica-map"]
		},
		{
			id: "reflection-email-consent-chain",
			fromName: "External Audit",
			fromEmail: "audit.external@helix.local",
			toName: "Helix Continuity Board",
			toEmail: "continuity.board@helix.local",
			subjectKey: "reflection.emails.consent.subject",
			subject: "Consent chain requested",
			bodyKey: "reflection.emails.consent.body",
			body: "",
			folder: "Inbox",
			sentAt: "2041-10-09T05:25:00.000Z",
			isFlagged: true,
			evidenceTags: ["audit-consent-chain"]
		}
	],
	chats: [
		{
			id: "reflection-chat-board-1",
			channel: "continuity-board",
			threadTitleKey: "reflection.chats.continuityBoard.title",
			sender: "Board-3",
			handle: "board.3",
			messageKey: "reflection.chats.continuityBoard.messages.first",
			sentAt: "2041-10-09T05:16:00.000Z",
			sequence: 1,
			isEncrypted: false,
			evidenceTags: ["continuity-board-minutes"]
		},
		{
			id: "reflection-chat-board-2",
			channel: "continuity-board",
			threadTitleKey: "reflection.chats.continuityBoard.title",
			sender: "Board-1",
			handle: "board.1",
			messageKey: "reflection.chats.continuityBoard.messages.second",
			sentAt: "2041-10-09T05:17:00.000Z",
			sequence: 2,
			isEncrypted: false,
			evidenceTags: ["board-000-signature", "omega-7-directive"]
		},
		{
			id: "reflection-chat-r7-1",
			channel: "reflection-lab-night",
			threadTitleKey: "reflection.chats.reflectionLabNight.title",
			sender: "R-7 Tech",
			handle: "r7.tech",
			messageKey: "reflection.chats.reflectionLabNight.messages.first",
			sentAt: "2041-10-09T05:21:00.000Z",
			sequence: 1,
			isEncrypted: false,
			evidenceTags: ["r7-core-activity-log"]
		},
		{
			id: "reflection-chat-r7-2",
			channel: "reflection-lab-night",
			threadTitleKey: "reflection.chats.reflectionLabNight.title",
			sender: "R-7 Watch",
			handle: "r7.watch",
			messageKey: "reflection.chats.reflectionLabNight.messages.second",
			sentAt: "2041-10-09T05:22:00.000Z",
			sequence: 2,
			isEncrypted: false,
			evidenceTags: ["reflection-lab-blueprint"]
		},
		{
			id: "reflection-chat-ren-arendt-1",
			channel: "Ren-S.Arendt",
			threadTitleKey: "reflection.chats.renArendt.title",
			sender: "Elias Ren",
			handle: "e.ren",
			messageKey: "reflection.chats.renArendt.messages.first",
			sentAt: "2041-10-09T05:26:00.000Z",
			sequence: 1,
			isEncrypted: false,
			evidenceTags: ["behavioral-replica-map"]
		},
		{
			id: "reflection-chat-ren-arendt-2",
			channel: "Ren-S.Arendt",
			threadTitleKey: "reflection.chats.renArendt.title",
			sender: "Selene Arendt",
			handle: "s.arendt",
			messageKey: "reflection.chats.renArendt.messages.second",
			sentAt: "2041-10-09T05:27:00.000Z",
			sequence: 2,
			isEncrypted: false,
			evidenceTags: ["selene-arendt-statement"]
		},
		{
			id: "reflection-chat-security-r7-1",
			channel: "security-r7",
			threadTitleKey: "reflection.chats.securityR7.title",
			sender: "R-7 Security",
			handle: "r7.sec",
			messageKey: "reflection.chats.securityR7.messages.first",
			sentAt: "2041-10-09T05:31:00.000Z",
			sequence: 1,
			isEncrypted: false,
			evidenceTags: ["lock-777-record"]
		},
		{
			id: "reflection-chat-security-r7-2",
			channel: "security-r7",
			threadTitleKey: "reflection.chats.securityR7.title",
			sender: "R-7 Security",
			handle: "r7.sec",
			messageKey: "reflection.chats.securityR7.messages.second",
			sentAt: "2041-10-09T05:32:00.000Z",
			sequence: 2,
			isEncrypted: false,
			evidenceTags: ["mirror-prime-core"]
		}
	],
	media: [],
	logs: [
		{
			id: "reflection-board-000",
			level: "CRITICAL",
			source: "continuity-board",
			code: "BOARD-000",
			occurredAt: "2041-10-09T05:15:00.000Z",
			isFlagged: true,
			evidenceTags: ["board-000-signature", "omega-7-directive"]
		},
		{
			id: "reflection-prime-617",
			level: "WARN",
			source: "mirror-prime",
			code: "PRIME-617",
			occurredAt: "2041-10-09T05:19:00.000Z",
			isFlagged: true,
			evidenceTags: ["mirror-prime-core", "replica-integrity-report"]
		},
		{
			id: "reflection-r7-core-404",
			level: "WARN",
			source: "reflection-core",
			code: "R7-CORE-404",
			occurredAt: "2041-10-09T05:23:00.000Z",
			isFlagged: true,
			evidenceTags: ["r7-core-activity-log", "reflection-lab-blueprint"]
		},
		{
			id: "reflection-audit-310",
			level: "INFO",
			source: "audit-vault",
			code: "AUDIT-310",
			occurredAt: "2041-10-09T05:00:00.000Z",
			isFlagged: true,
			evidenceTags: ["audit-consent-chain"]
		},
		{
			id: "reflection-relay-omega",
			level: "ERROR",
			source: "relay-omega",
			code: "RELAY-OMEGA",
			occurredAt: "2041-10-09T05:28:00.000Z",
			isFlagged: true,
			evidenceTags: ["relay-omega-isolation-log", "omega-7-directive"]
		},
		{
			id: "reflection-merge-909",
			level: "CRITICAL",
			source: "reflection-core",
			code: "MERGE-909",
			occurredAt: "2041-10-09T05:33:00.000Z",
			isFlagged: true,
			evidenceTags: ["merge-909-export-trace", "mirror-prime-core"]
		},
		{
			id: "reflection-lock-777",
			level: "WARN",
			source: "mirror-prime",
			code: "LOCK-777",
			occurredAt: "2041-10-09T05:38:00.000Z",
			isFlagged: true,
			evidenceTags: ["lock-777-record"]
		}
	]
};
